<?php

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
		'key' => 'group_6480a268b7fa2',
		'title' => 'Blog Post Meta',
		'fields' => array(
			array(
				'key' => 'field_6480a269ca436',
				'label' => 'Author(s) Attribution',
				'name' => 'authorship',
				'aria-label' => '',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'person',
				),
				'post_status' => array(
					0 => 'publish',
				),
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
					1 => 'post_type',
				),
				'return_format' => 'object',
				'min' => '',
				'max' => '',
				'elements' => '',
			),
			array(
				'key' => 'field_6480a8aef883e',
				'label' => 'Choice',
				'name' => 'choice',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );

	acf_add_local_field_group( array(
		'key' => 'group_6480d919894ff',
		'title' => 'Blog Settings',
		'fields' => array(
			array(
				'key' => 'field_6480d9199dbaf',
				'label' => 'About The Blog Page',
				'name' => '',
				'aria-label' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'This page is not directly editable. It is populated dynamically.',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_648224f604b44',
				'label' => 'Featured',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_6482254e04b46',
				'label' => 'Featured Posts',
				'name' => 'featured_posts',
				'aria-label' => '',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'post',
				),
				'post_status' => '',
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
					1 => 'post_type',
					2 => 'taxonomy',
				),
				'return_format' => 'object',
				'min' => '',
				'max' => 2,
				'elements' => '',
			),
			array(
				'key' => 'field_6482251d04b45',
				'label' => 'Featured 2',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page',
					'operator' => '==',
					'value' => '27',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'permalink',
			1 => 'the_content',
			2 => 'excerpt',
			3 => 'discussion',
			4 => 'comments',
			5 => 'revisions',
			6 => 'slug',
			7 => 'author',
			8 => 'format',
			9 => 'featured_image',
			10 => 'categories',
			11 => 'tags',
			12 => 'send-trackbacks',
		),
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );

	acf_add_local_field_group( array(
		'key' => 'group_6480aaaf9135d',
		'title' => 'Highlight Settings',
		'fields' => array(
			array(
				'key' => 'field_6480aaaf5ddcb',
				'label' => 'Display at Top of Site?',
				'name' => 'display_at_top_of_site',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_6480aad95ddcc',
				'label' => 'Display on Page(s)',
				'name' => 'display_on_pages',
				'aria-label' => '',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_6480aaaf5ddcb',
							'operator' => '!=',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'page',
				),
				'post_status' => '',
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
					1 => 'post_type',
					2 => 'taxonomy',
				),
				'return_format' => 'object',
				'min' => '',
				'max' => '',
				'elements' => '',
			),
			array(
				'key' => 'field_6480aaf75ddcd',
				'label' => 'Display on Blog Post(s)',
				'name' => 'display_on_blog_posts',
				'aria-label' => '',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_6480aaaf5ddcb',
							'operator' => '!=',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'post',
				),
				'post_status' => '',
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
					1 => 'post_type',
					2 => 'taxonomy',
				),
				'return_format' => 'object',
				'min' => '',
				'max' => '',
				'elements' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'highlight',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );

	acf_add_local_field_group( array(
		'key' => 'group_647f8b1f56cc3',
		'title' => 'Page Header',
		'fields' => array(
			array(
				'key' => 'field_647f8b22f7ab7',
				'label' => 'Lead In Copy',
				'name' => 'lead_in_copy',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'visual',
				'toolbar' => 'basic',
				'media_upload' => 0,
				'delay' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );

	acf_add_local_field_group( array(
		'key' => 'group_6480da1570ec5',
		'title' => 'Post Header',
		'fields' => array(
			array(
				'key' => 'field_6480da157f6e8',
				'label' => 'Lead In Copy',
				'name' => 'lead_in_copy',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'visual',
				'toolbar' => 'basic',
				'media_upload' => 0,
				'delay' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );

	acf_add_local_field_group( array(
		'key' => 'group_6480a905ce5e2',
		'title' => 'Sidebar Settings',
		'fields' => array(
			array(
				'key' => 'field_6480a9060af02',
				'label' => 'Enable Menu?',
				'name' => 'enable_menu',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_6480a91e0af03',
				'label' => 'Menu',
				'name' => 'menu',
				'aria-label' => '',
				'type' => 'menu-chooser',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_6480a9060af02',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
				array(
					'param' => 'page',
					'operator' => '!=',
					'value' => '27',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );
} );

add_action( 'init', function() {
	register_post_type( 'highlight', array(
		'labels' => array(
			'name' => 'Highlights',
			'singular_name' => 'Highlight',
			'menu_name' => 'Highlights',
			'all_items' => 'All Highlights',
			'edit_item' => 'Edit Highlight',
			'view_item' => 'View Highlight',
			'view_items' => 'View Highlights',
			'add_new_item' => 'Add New Highlight',
			'new_item' => 'New Highlight',
			'parent_item_colon' => 'Parent Highlight:',
			'search_items' => 'Search Highlights',
			'not_found' => 'No highlights found',
			'not_found_in_trash' => 'No highlights found in Trash',
			'archives' => 'Highlight Archives',
			'attributes' => 'Highlight Attributes',
			'insert_into_item' => 'Insert into highlight',
			'uploaded_to_this_item' => 'Uploaded to this highlight',
			'filter_items_list' => 'Filter highlights list',
			'filter_by_date' => 'Filter highlights by date',
			'items_list_navigation' => 'Highlights list navigation',
			'items_list' => 'Highlights list',
			'item_published' => 'Highlight published.',
			'item_published_privately' => 'Highlight published privately.',
			'item_reverted_to_draft' => 'Highlight reverted to draft.',
			'item_scheduled' => 'Highlight scheduled.',
			'item_updated' => 'Highlight updated.',
			'item_link' => 'Highlight Link',
			'item_link_description' => 'A link to a highlight.',
		),
		'public' => true,
		'show_in_rest' => true,
		'supports' => array(
			0 => 'title',
			1 => 'editor',
		),
		'delete_with_user' => false,
	) );

	register_post_type( 'person', array(
		'labels' => array(
			'name' => 'People',
			'singular_name' => 'Person',
			'menu_name' => 'People',
			'all_items' => 'All People',
			'edit_item' => 'Edit Person',
			'view_item' => 'View Person',
			'view_items' => 'View People',
			'add_new_item' => 'Add New Person',
			'new_item' => 'New Person',
			'parent_item_colon' => 'Parent Person:',
			'search_items' => 'Search People',
			'not_found' => 'No people found',
			'not_found_in_trash' => 'No people found in Trash',
			'archives' => 'Person Archives',
			'attributes' => 'Person Attributes',
			'insert_into_item' => 'Insert into person',
			'uploaded_to_this_item' => 'Uploaded to this person',
			'filter_items_list' => 'Filter people list',
			'filter_by_date' => 'Filter people by date',
			'items_list_navigation' => 'People list navigation',
			'items_list' => 'People list',
			'item_published' => 'Person published.',
			'item_published_privately' => 'Person published privately.',
			'item_reverted_to_draft' => 'Person reverted to draft.',
			'item_scheduled' => 'Person scheduled.',
			'item_updated' => 'Person updated.',
			'item_link' => 'Person Link',
			'item_link_description' => 'A link to a person.',
		),
		'public' => true,
		'show_in_rest' => true,
		'supports' => array(
			0 => 'title',
			1 => 'editor',
			2 => 'thumbnail',
		),
		'delete_with_user' => false,
	) );
} );
